version: "2"
volumes:
  db-postgresdb:
  db-mongodb:
  mq-activemq:

services:

  activemq:
    image: webcenter/activemq:latest
    hostname: activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
    - mq-activemq:/opt/activemq
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"

  backend:
    build:
      context: backend
    ports:
      - "8085:8080"
      - "9225:9221"
    env_file:
      - .env

  order-postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: event-driven-order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db-postgresdb:/var/lib/order-postgresdb/data
    ports:
      - "5435:5432"

  order:
    build:
      context: order
    ports:
      - "8086:8080"
      - "9226:9221"
    depends_on:
      - order-postgresdb
    env_file:
      - .env

  inventory-mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event-driven-inventory
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db-mongodb:/inventory-mongodb/data/db
    ports:
      - "27010:27017"

  inventory:
    build:
      context: inventory
    ports:
      - "8087:8080"
      - "9227:9221"
    depends_on:
      - inventory-mongodb
    env_file:
      - .env