version: "2"
volumes:
  db-postgresdb:
  db-mongodb:

services:

  backend:
    build:
      context: backend
    ports:
      - "8085:8085"
      - "9225:9225"
    env_file:
      - .env

  order-postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: event-driven-order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db-postgresdb:/var/lib/order-postgresdb/data
    ports:
      - "5435:5432"

  order:
    build:
      context: order
    ports:
      - "8086:8086"
      - "9226:9226"
    depends_on:
      - order-postgresdb
    env_file:
      - .env

  inventory-mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event-driven-inventory
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db-mongodb:inventory-mongodb/data/db
    ports:
      - "27010:27017"

  inventory:
    build:
      context: inventory
    ports:
      - "8087:8087"
      - "9227:9227"
    depends_on:
      - inventory-mongodb
    env_file:
      - .env