version: "2.4"
volumes:
  order-postgresdb:
  amazon-mongodb:
  inventory-mongodb:
  mq-activemq:

services:

  activemq:
    image: webcenter/activemq:latest
    hostname: activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - mq-activemq:/opt/activemq
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"

  client:
    environment:
      REACT_APP_API_END_POINT_URL: http://localhost:8085/v1
      NODE_ENV: development
    build:
      context: client
    ports:
      - "3010:3000"
      - "9210:9220"
    depends_on:
      - backend
    command: npm start
    volumes:
      - ./client:/boot-camp-event-driven/client
      - /boot-camp-event-driven/client/node_modules/
    env_file:
      - .env
    tty: true

  backend:
    build:
      context: backend
    ports:
      - "8085:8080"
      - "9225:9221"
    env_file:
      - .env

  order-postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: event-driven-order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - order-postgresdb:/var/lib/order-postgresdb/data
    ports:
      - "5435:5432"

  order:
    build:
      context: order
    ports:
      - "8086:8080"
      - "9226:9221"
    depends_on:
      - order-postgresdb
    env_file:
      - .env

  inventory-mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event-driven-inventory
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - inventory-mongodb:/inventory-mongodb/data/db
    ports:
      - "27010:27017"

  inventory:
    build:
      context: inventory
    ports:
      - "8087:8080"
      - "9227:9221"
    depends_on:
      - inventory-mongodb
    env_file:
      - .env

  amazon-mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event-driven-amazon
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - amazon-mongodb:/amazon-mongodb/data/db
    ports:
      - "27011:27017"

  amazon:
    build:
      context: amazon
    ports:
      - "8088:8080"
      - "9228:9221"
    depends_on:
      - amazon-mongodb
    env_file:
      - .env

  fake-amazon:
    build:
      context: fake-amazon
    ports:
      - "8089:8080"
      - "9229:9221"
    env_file:
      - .env